const nome = prompt('Qual seu nome?')
const dataNascimento = prompt('Qual sua data de nascimento?(Utilize as /)')
const endereco = prompt('Qual seu endereço?')
const cpf = Number(prompt('Qual seu CPF?'))
const escolaridade = prompt('Qual sua escolaridade?')
const cnh = prompt('Você possui CNH?')
const qtFilhos = Number(prompt('Quantos filhos você possui?'))
const cargoAtual = prompt('Qual seu cargo atual?')
const salario = Number(prompt('Qual seu salário?'))
const comissao = Number(prompt('Você recebe comissão? Se sim, informe a porcentagem, caso não, responda com zero.'))
const anoAdmissao = Number(prompt('Qual seu ano de admissão?'))


console.log('OS TIPOS SÃO:')
console.log(typeof nome)
console.log(typeof dataNascimento)
console.log(typeof endereco)
console.log(typeof cpf)
console.log(typeof escolaridade)
console.log(typeof cnh)
console.log(typeof qtFilhos)
console.log(typeof cargoAtual)
console.log(typeof salario)
console.log(typeof comissao)
console.log(typeof anoAdmissao)

console.log('RELATÓRIO:')
console.log('Nome:', nome)
console.log('Data de Nascimento:', dataNascimento)
console.log('Endereço:', endereco)
console.log('CPF:', cpf)
console.log('Escolaridade:', escolaridade)
console.log('CNH:', cnh)
console.log('Número de filhos:', qtFilhos)
console.log('Cargo atual:', cargoAtual)
console.log('Salário', salario)
console.log('Comissão:', comissao)
console.log('Ano de admissão:', anoAdmissao)